# Generated by Django 5.0.7 on 2024-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_educational_group', models.BooleanField(default=False)),
                ('educational_group_name', models.TextField(blank=True, null=True)),
                ('priced_units_quantity', models.TextField(blank=True, null=True)),
                ('pricing_type', models.TextField(blank=True, null=True)),
                ('school_cnpj', models.TextField(blank=True, null=True)),
                ('trade_name', models.TextField(blank=True, null=True)),
                ('corporate_name', models.TextField(blank=True, null=True)),
                ('inep_code', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data_attachment', models.FileField(blank=True, null=True, upload_to='attachments/data/')),
                ('contract_attachment', models.FileField(blank=True, null=True, upload_to='attachments/contract/')),
                ('history', models.TextField(blank=True, null=True)),
                ('partner_confirmation', models.TextField(blank=True, null=True)),
                ('physical_structure_attachment', models.FileField(blank=True, null=True, upload_to='attachments/physical_structure/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
