# Generated by Django 5.0.7 on 2024-07-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_ticket_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='demand.pricingticketunit')),
            ],
        ),
    ]
