# Generated by Django 5.0.7 on 2024-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='ticket_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
