# Generated by Django 5.0.7 on 2024-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='approved_kedu_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='priced_kedu_fee',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='priced_units_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
