# Generated by Django 5.0.7 on 2024-07-23 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_pricing_approved_kedu_fee_pricing_priced_kedu_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('unit_quantity', models.PositiveIntegerField()),
                ('pricing_type', models.CharField(choices=[('Agrupada', 'Taxa Agrupada'), ('Por Unidade', 'Taxa por Unidade')], max_length=11)),
                ('selected_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.pricinggroup')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('fantasy_name', models.CharField(max_length=255)),
                ('social_reason', models.CharField(max_length=255)),
                ('inep_code', models.CharField(blank=True, max_length=12, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True, null=True)),
                ('history_description', models.TextField(blank=True, null=True)),
                ('commercial_partners', models.BooleanField()),
                ('partner_details', models.TextField(blank=True, null=True)),
                ('history_profile', models.TextField(blank=True, null=True)),
                ('data_attachments', models.FileField(blank=True, null=True, upload_to='data_attachments/')),
                ('contract_attachment', models.FileField(blank=True, null=True, upload_to='contract_attachments/')),
                ('school_structure_attachments', models.FileField(blank=True, null=True, upload_to='school_structure_attachments/')),
                ('pricing_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='demand.pricingticket')),
            ],
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
