# Generated by Django 5.0.7 on 2024-07-23 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pricing_ticket_unit',
        ),
        migrations.AddField(
            model_name='comment',
            name='pricing_ticket',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='demand.pricingticket'),
            preserve_default=False,
        ),
    ]
