# Generated by Django 5.0.7 on 2024-07-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_alter_pricingticketunit_pricing_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='pricingticket',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='pricingticket',
            name='responsible_sector',
        ),
        migrations.RemoveField(
            model_name='pricingticket',
            name='status',
        ),
        migrations.AddField(
            model_name='demand',
            name='responsible',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='responsible_sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
