# Generated by Django 5.0.7 on 2024-07-25 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_remove_demand_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='demand',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='responsible_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
