# Generated by Django 5.0.7 on 2024-07-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0005_demand_due_date_demand_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingticketunit',
            name='contract_attachments',
        ),
        migrations.RemoveField(
            model_name='pricingticketunit',
            name='data_attachments',
        ),
        migrations.RemoveField(
            model_name='pricingticketunit',
            name='school_structure_attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='demand.demand'),
            preserve_default=False,
        ),
    ]
