# Generated by Django 5.0.7 on 2024-07-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0007_attachment_type_attachment_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='unit',
        ),
    ]
