# Generated by Django 5.0.7 on 2024-07-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0008_remove_attachment_type_remove_attachment_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingticketunit',
            name='history_description',
        ),
        migrations.RemoveField(
            model_name='pricingticketunit',
            name='history_profile',
        ),
        migrations.RemoveField(
            model_name='pricingticketunit',
            name='partner_details',
        ),
    ]
