# Generated by Django 5.0.7 on 2024-07-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0009_remove_pricingticketunit_history_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingticket',
            name='group',
            field=models.CharField(max_length=5),
        ),
    ]
