# Generated by Django 5.0.7 on 2024-07-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0010_alter_pricingticket_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingticket',
            old_name='commercial_partners',
            new_name='partner_confirmation',
        ),
    ]
