# Generated by Django 5.0.7 on 2024-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
